server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:order_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:secret_password}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8080}

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 2